### ISSUE TITLE
Suggestion to maintain libraries as part of the project 

### ISSUE THREAD

**Issue by manoj153** [the-flame-trench/Singularity#16]
![image](https://user-images.githubusercontent.com/17961318/120890626-a133eb00-c636-11eb-886d-54f75110283a.png)

I prefer to keep as a single repo, and without  a need of defining a custom path. Above is a project I work on where it could be open on any computer. 

p.s I can write embedded C code and design electronics, let's discuss if you're happy to allow me contribute in this project.

**Comment by TFT-Ben** [comment]
We use this library structure to ensure that a) when you open the repo, you are guaranteed to be looking at the latest libraries and b) to centralise our component libraries allowing for easy and consistent re-use. Hosting libraries on a per-project basis would not allow this. 

As for contributing, [here](https://discord.gg/Ryx5U2Sf) is the link to our Discord that we use for coordination
